#!/bin/bash

DIR="$(dirname "$0")"

TAG=${1:-latest}

MACHINE="lean-auto-artifact"
REGISTRY="public.ecr.aws/a9g8a7m1"
REPO="lean-auto-artifact"
IMAGE="$REGISTRY/$REPO:$TAG"

eval "$DIR/docker-login" "$MACHINE" && \
ssh "$MACHINE" "rm -rf build-$REPO && mkdir build-$REPO" && \
  git archive HEAD | zstdcat | ssh "$MACHINE" "zstdcat -d | tar -C build-$REPO -xf -" && \
  ssh "$MACHINE" "cd build-$REPO && sudo docker build . -t $IMAGE --network host"
