#!/bin/bash

MACHINE="${1:-lean-auto-artifact}"
REGION="eu-central-1"
AWS_PROFILE="personal"
REGISTRY="605134433106.dkr.ecr.eu-central-1.amazonaws.com"

aws --profile "$AWS_PROFILE" ecr get-login-password --region "$REGION" | ssh "$MACHINE" sudo docker login --username AWS --password-stdin "$REGISTRY"
